# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-21 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0140_remove_profile_url_and_fix_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile_image_url',
        ),
    ]
