# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-19 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_metadata', '0140_remove_profile_url_and_fix_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
